import type { Metadata } from "next";
import { Alegreya_Sans } from "next/font/google";
import "./globals.css";

const manrope = Alegreya_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={manrope.className}
      style={{ scrollbarGutter: "auto" }}
    >
      <body className="min-h-svh" suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
